POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2OThlYzJiYjA5YTQ2YzM5NjkzYjk5ZSIsImlhdCI6MTcyMjMzODQ2NH0.oTLDtPRWQx-g8tXTtI7FRrVQ8u9Lad-5PZgpA5PoS0I

{
  "title": "monke",
  "author": "yes",
  "url": "monke.com",
  "likes": 5
}