POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpIiwiaWQiOiI2NmIzNWNmNzdlOTg0YzQ5NmM0ZGY0NjUiLCJpYXQiOjE3MjMwMzA3OTQsImV4cCI6MTcyMzAzNDM5NH0.ds4ohVELeRbDIQRrLeOQncLRl4G4sq2B_-rsheiD0xA

{
  "title": "testaappa",
  "author": "testiboi",
  "url": "testi.fi",
  "likes": 2
}