DELETE http://localhost:3003/api/blogs/66a9e9170b024c082ea04594
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2OThlYzJiYjA5YTQ2YzM5NjkzYjk5ZSIsImlhdCI6MTcyMjQxMTAxNSwiZXhwIjoxNzIyNDE0NjE1fQ.jmHMU35phxL_ajVeqVQJBHe5k8fgz-nxfc4MutYNKYY
